#!/bin/bash

# Start the database container in the background
docker compose up db -d

# Start an interactive shell in the webengine container with the current directory mounted
# ..include optional arguments such as create or start
docker compose run --rm -it -p 8080:8080 -v ${PWD}/app:/usr/src/app --entrypoint "bash" webengine

# Clean up after we are finished
docker compose down
sudo chown -R ${UID:-1000}:${GID:-1000} ${PWD}/app
