#!/bin/bash

# Start the database container in the background
docker compose up db -d

echo "Updating the database scheme..."
docker compose run --rm -it -p 8080:8080 -v ${PWD}/app:/usr/src/app --entrypoint "python manage.py migrate" webengine

echo "Collecting static files..."
docker compose run --rm -it -p 8080:8080 -v ${PWD}/app:/usr/src/app --entrypoint "python manage.py collectstatic --noinput" webengine

echo "Starting the Django development server..."
docker compose run --rm -it -p 8080:8080 -v ${PWD}/app:/usr/src/app --entrypoint "python manage.py runserver 0.0.0.0:8080" webengine

# Clean up after we are finished
docker compose down
sudo chown -R ${UID:-1000}:${GID:-1000} ${PWD}/app
